== Browsers Supported

PMS Revamp Portal web application is currently compatible and certified
with the following list of browsers as part of PMS 1.3.0.beta.1 release:

*Browser Versions - Desktop/Laptop*

Sl. No

Browser

Version

Chrome

Version 133.0.6943.127 and above

Firefox

Version 135.0.1 and above

Edge

Version 133.0.3065.82 and above

Safari

Version 18.3 and above

*Browser Versions - Tablet*

Sl. No

Browser

Version

Chrome

Version 133.0.6943.121 and above

Firefox

Version 135.0.1 and above

Edge

Version 133.0.3065.67 and above

Safari

Version and above

*Browser Versions for Extra large screen*

Sl. No

Browser

Version

Chrome

Version 133.0.6943.127 and above

Firefox

Version 135.0.1 and above

Edge

Version 133.0.3065.82 and above

Safari

Version 18.3 and above

Tested on following Screen sizes for validating UI responsiveness as
part of PMS 1.3.0.beta.1 release:

* *Windows Laptop/Desktop*: 1920x1080
* *Tablet*: 1280X800
* *Extra-large screens*: 3840x2160
* *Mac book*: 2560 x 1664
