== Module Configurations

=== Overview

Properties that are shared across all modules are written in the file
https://github.com/mosip/mosip-config/blob/release-1.2.0/application-default.properties[`application-default.properties`].

Module-specific properties are written in respective `++*++.properties`
files in
https://github.com/mosip/mosip-config/blob/release-1.2.0[mosip-config]

=== Config server

Config server is a
https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_server.html[Spring
Cloud Config Server] that serves the above properties to modules during
run-time. The property files are downloaded when an application starts.
The config server is installed as part of
link:../../broken-reference/[sandbox installation].

Some of the important properties that must be reviewed and modified for
a specific deployment are listed below.

=== Modules

Configurations of each MOSIP module will be available here:

* Administration
* Commons
* Datashare
* link:../identity-verification/id-authentication-services/#configuration[ID
Authentication]
* ID Repository
* Key Manager
* Packet Manager
* Partner Management
* Pre-registration
* link:../identity-issuance/registration-client/#configurations[Registration
Client]
* link:../identity-issuance/registration-processor/#configurations[Registration
Processor]
* Resident Services
* Resident Mobile Application
* WebSub

=== Database

Refer to
link:../supporting-components/persistence/postgres-db.md#configuration-parameters[Postgres
DB configuration].

=== HSM

Refer to link:keymanager/hsm.md#configuration[HSM configuration].

=== Languages

*Mandatory Languages* - Languages that the user has to fill (can be auto
translated) during the pre-registration & registration.

*Optional Languages* - Languages that are not mandatory but provided as
a choice to the user.

*User selected Language* - The language that the user selected at the
time of login. The choices shown are union of Mandatory and Optional
languages. The labels and alerts will be use the user selected language

*Prefered Language* - During registration of a registrant (user for whom
identity is requested), he can choose his prefered language. This
preference use used for all further notification (email, SMS or any
other notification).

Languages for the entire system are configured in application
prorperties file:

....
mosip.mandatory-languages=eng,tam
mosip.optional-languages=fra,ara
....

____
The i18n file for the respective language has to be added to the
artifactory https://github.com/mosip/artifactory-ref-impl[Artifactory].
The language codes are as per
https://www.loc.gov/standards/iso639-2/php/code_list.php[ISO 639-2]
____
