== Administration

=== Overview

The MOSIP platform is configured via the Admin application. This
application can be accessed only by a privileged group of administration
personnel. The admin module provides the following functions:

[arabic]
. Management of resources via CRUD operations:
[arabic]
.. Zone
.. Centers (registration centers)
.. Device
.. Machine
.. Users (Admin, registration staff)
. Registration administration
[arabic]
.. Packet status
.. Retrieve lost RID
.. Resume RID

=== Administrative zones

* Administrative zones are virtual boundaries which a country can define
to better manage their resources that are used during registrations.
These resources includes Centers, Users, Machines and Devices. These
zones can be defined in a hierarchical fashion and a country can
allocate resources to such zones based on their requirements.
* Resources under each zone is managed by a _Zonal Admin_. This is done
by assigning an Administrative zone to the Zonal Admin during user
creation.
* These Zonal Admins can exist at any zonal hierarchy. (For e.g, a Zonal
Admin can directly be mapped to the whole country as a Zone or can be
mapped to a significantly smaller zone such as a city). Thus, these
resources when mapped to an Administrative zone can only be managed by
the Admin of that zone.

=== Activate/deactivate/decommission resources

==== What is deactivation of a resource?

Deactivation refers to a reversible action in which the isActive value
for a resource in database is set to "`False`". This means that the
resource will not be available for use unless and until it is activated
later through the admin portal as required by the country.

==== What is decommissioning a resource?

* Decommission refers to a permanent/irreversible action of the
resource. This also automatically deactivates it and the isDeleted value
for the resource is set to "`True`".
* The primary difference being that a decommissioned resource cannot be
bought into commission again as decommission refers to a permanent
shutdown.
* Also, in cases where a center has some resources mapped to it
(e.g. machines, devices or users), the portal will not allow the admin
to decommission such a center.

_Note- Activation/Deactivation/Decommission of a center in one language
will be applied to the same center created in all the languages._

=== Services

[arabic]
. https://github.com/mosip/admin-services/tree/release-1.2.0/admin/admin-service[Admin
Service]
. https://github.com/mosip/admin-services/tree/release-1.2.0/admin/hotlist-service[Hotlist
Service]
. https://github.com/mosip/admin-services/tree/release-1.2.0/admin/kernel-masterdata-service[kernel
Masterdata Service]
. https://github.com/mosip/admin-services/tree/release-1.2.0/admin/kernel-syncdata-service[Kernel
Syncdata Service]

=== Frontend- Admin portal

Reference implementation of the Admin portal is available in
https://github.com/mosip/admin-ui/tree/master[admin-ui] repository.

To know more, refer to the link:test/admin-portal-user-guide.md[Admin
portal user guide].

=== Developer Guide

To know more about the setup, read
https://docs.mosip.io/1.2.0/modules/administration/admin-services-developers-guide[Admin
Services Developer’s Guide].

=== API

Refer https://mosip.github.io/documentation/1.2.0/1.2.0.html[API
Documentation].

=== Source code

https://github.com/mosip/admin-services/tree/release-1.2.0[Github repo].
