== Overview

=== Overview

The Android Registration Client is a tablet application that serves as a
portable version of the existing desktop
https://docs.mosip.io/1.2.0/modules/registration-client[Registration
Client]. It has been developed to support accessibility on all Android
devices. The creation of the Android Registration Client was driven by
the need to meet the mobility requirements of countries adopting MOSIP.

The primary objective of the tablet version is to facilitate the
registration process for residents, especially those who are unable to
physically visit registration centers. It also serves remote locations
where setting up registration centers is not feasible. To address this
challenge, the Android Registration Client was created, enabling
operators and supervisors to easily reach remote areas and maximize
resident registrations across the country.

==== Configuration Guide

To read through the comprehensive list of configurable properties for
the Android Registration Client, refer
https://docs.mosip.io/1.2.0/android-registration-client/android-registration-client-configuration[Android
Registration Client Configuration Guide].

==== UI Specifications

For more details on UI specifications for the Android Registration
Client, refer link:../develop/ui-spec-documentation.md[here].

==== Compatibility

The Android Registration Client is compatible with the following MOSIP
platform versions:

[arabic]
. 1.1.5.x
. LTS 1.2.0 and above
