== ID Lifecycle Management

=== Overview

Identity Lifecycle Management refers to *issuing and managing user
identities* in a given system. An individual can visit a registration
centre to get a new ID or update their ID details. A registration
officer would typically capture the individual’s demographic (name, date
of birth, gender, etc.) and biometric (face, iris, and fingerprint
image) details.

The lifecycle of an identity involves multiple events, categorized into
different stages, each managed within specific system *modules*. The
following sections outline these *key lifecycle events*, detailing their
roles and functions categorized under relevant modules. +
 +
Browse the cards below to *explore the various applications and
services* that support Identity Lifecycle Management.

nav-card-identity-issuance.png

identity-issuance

nav-card-Identity-verification.png

identity-verification

v-identity-management.png

identity-management

nav-card-support-systems.png

support-systems
