== Automation Testing

=== Overview

MOSIP provides automation test repositories for the following:

* https://github.com/mosip/admin-ui/tree/release-1.2.0/admintest[Admin
UI]
* https://github.com/mosip/registration-client/tree/release-1.2.0/registration/registration-test[Registration
Client]
* https://github.com/mosip/mosip-functional-tests/tree/release-1.2.0[Functional
Tests]
* https://github.com/mosip/mosip-automation-tests/tree/release-1.2.0[Automation
Tests]

==== Admin UI

Selenium webdriver-based Admin Portal Automation covers CRUD (create,
read, update and delete) operation performed via UI with Chrome driver.

==== Registration Client

Registration test automation covers these flows: New, Update,
Correction, and Lost flows.

To know more about each, click link:../../../[here].

==== Functional Tests

This repository contains API automation tests. The automation is written
using Java REST Assured and TestNG framework. The following modules are
covered:

[arabic]
. Pre-registration
. Masterdata
. Partner Management
. ID Repository
. IDA
. Resident

Functional tests support multi-languages, i.e., the input can be
provided in any of the languages configured in a given MOSIP
installation.

==== Automation Tests

This repository contains a test framework for end-to-end testing of
MOSIP functionality. The following functionalities are covered:

* Registration
* Pre-registration {plus} Registration
* Authentication
